name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Go mod download
      run: go mod download
    - name: Install mockgen
      run: go install github.com/golang/mock/mockgen@v1.6.0
    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo
    
    - name: mockgen
      run: make mockgen

    - name: Run unit tests
      run: make unit-test
