name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Get Ginkgo
      run: go get github.com/onsi/ginkgo/v2/ginkgo
        
    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo

    - name: Run unit tests
      run: make unit-test
